### ISSUE TITLE
ProactorEventLoop is not supported

### ISSUE THREAD

**Issue by Mennaruuk** [requests/requests-threads#14]
I get this error:
```
Traceback (most recent call last):
  File "C:\Users\Menna\Desktop\requests-futures\twayback.py", line 3, in <module>
    session = AsyncSession(n=100)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_threads.py", line 37, in __init__
    asyncioreactor.install(loop)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\asyncioreactor.py", line 308, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\asyncioreactor.py", line 63, in __init__
    raise TypeError(
TypeError: ProactorEventLoop is not supported, got: <ProactorEventLoop running=False closed=False debug=False>
```

upon running the following Python script:
`https://pastebin.com/raw/xrujJmSu`

Use the following example command if you'd like to run the script:
`script.py -u jack -from 20220205 -to 20220206`

**Comment by hansalemaos** [comment]
I have had the same problem. 
This here seems to work:

`import asyncio, sys

if sys.platform == 'win32':
    loop = asyncio.SelectorEventLoop()
    asyncio.set_event_loop(loop)

from twisted.internet.defer import inlineCallbacks
from twisted.internet.task import react
from requests_threads import AsyncSession
session = AsyncSession(n=100)


@inlineCallbacks
def main(reactor):
    responses = []
    for i in range(100):
        responses.append(session.get('http://httpbin.org/get'))

    for response in responses:
        r = yield response
        print(r)

if __name__ == '__main__':
    react(main)`
